name: Teste – Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  security:
    # Use o caminho exato do arquivo e uma ref existente (main ou sua tag)
    uses: JNDEVSEC/security-templates/.github/workflows/security_scan.yaml@main
    secrets: inherit
    with:
      # Se for monorepo, aponte a subpasta; para raiz, use '.'
      project-path: '.'
#
