name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  security:
    uses: JNDEVSEC/security-templates/.github/workflows/security-scan.yml@v1
    secrets: inherit
